Repository KhronosGroup/Vulkan-Utility-Libraries, pull requests merged in 2023-09, with the labels that each got.

#91 layer: Add 'on' and 'off' for bool layer settings for API dump comp
  src/layer/vk_layer_settings.cpp
Labels: enhancement, P1, OS - Platform Independent

#98 cmake: Add a function to setup all build targets with the same strictness
  CMakeLists.txt
  include/CMakeLists.txt
  scripts/CMakeLists.txt
  src/layer/CMakeLists.txt
  src/layer/vk_layer_settings.cpp
  tests/add_subdirectory/vk_enum_string_helper.c
  tests/generated/CMakeLists.txt
  tests/layer/CMakeLists.txt
  tests/layer/test_setting_env.cpp
  tests/layer/test_setting_util.cpp
  tests/vul_dispatch_table/CMakeLists.txt
Labels: enhancement, P1, OS - Platform Independent

#100 Ensure all header files shipped have the vk_ prefix
  .github/workflows/ci.yml
  BUILD.gn
  docs/generated_code.md
  include/CMakeLists.txt
  include/vulkan/utility/vk_dispatch_table.h
  scripts/generate_source.py
  tests/CMakeLists.txt
  tests/README.md
  tests/add_subdirectory/CMakeLists.txt
  tests/add_subdirectory/vk_dispatch_table.c
  tests/add_subdirectory/vk_enum_string_helper.c
  tests/add_subdirectory/vk_layer_settings.c
  tests/find_package/CMakeLists.txt
  tests/vk_dispatch_table/CMakeLists.txt
  tests/vk_dispatch_table/test_interface.cpp
  tests/vul_dispatch_table/CMakeLists.txt
Labels: enhancement, build

#108 layer: Add features to list unknown settings
  include/vulkan/layer/vk_layer_settings.h
  src/layer/vk_layer_settings.cpp
  tests/layer/test_setting_util.cpp
Labels: enhancement, P1, OS - Platform Independent

#111 layer: Simplify code using vkGetUnknownSettings
  src/layer/vk_layer_settings.cpp
Labels: enhancement, P2, OS - Platform Independent

#112 layer: Add CPP version of GetUnknownSettings
  include/vulkan/layer/vk_layer_settings.hpp
  src/layer/vk_layer_settings.cpp
  tests/layer/test_setting_cpp.cpp
  tests/layer/test_setting_util.cpp
Labels: enhancement, P2, OS - Platform Independent

#115 cmake: Add unreachable code check with GCC and Clang
  scripts/CMakeLists.txt
Labels: enhancement, P2, OS - Platform Independent

#116 layer: Add env var prefix override for back compatibility
  include/vulkan/layer/vk_layer_settings.h
  scripts/CMakeLists.txt
  src/layer/layer_settings_manager.cpp
  src/layer/layer_settings_manager.hpp
  src/layer/layer_settings_util.cpp
  src/layer/layer_settings_util.hpp
  src/layer/vk_layer_settings.cpp
  tests/layer/test_setting_env.cpp
  tests/layer/test_setting_util.cpp
Labels: bug, enhancement, P1, OS - Platform Independent

#85 docs: Add layer configuration documentation
  docs/layer_configuration.md
Labels: documentation, P1, OS - Platform Independent

#119 layer: Add multiple VkLayerSettingsCreateInfo support
  include/vulkan/layer/vk_layer_settings.h
  include/vulkan/layer/vk_layer_settings.hpp
  src/layer/layer_settings_manager.cpp
  src/layer/layer_settings_manager.hpp
  src/layer/vk_layer_settings.cpp
  src/layer/vk_layer_settings_helper.cpp
  tests/layer/test_setting_api.cpp
  tests/layer/test_setting_util.cpp
Labels: enhancement, P1, OS - Platform Independent

#120 doc: Update README.md with project description
  README.md
  docs/vulkan_layer_settings.md
Labels: documentation
